services:
    db-clientes:
      image: postgres:15
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: clientes_db

      ports:
        - "5432:5432"

    db-inventario:
      image: postgres:15
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: inventario_db

      ports:
        - "5433:5432"

    db-pedidos:
      image: postgres:15
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: pedidos_db

      ports:
        - "5434:5432"