server:
  port: 8081

spring:
  application:
    name: servicio-clientes
  datasource:
    url: jdbc:postgresql://localhost:5432/clientes_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
